[phases.setup]
nixPkgs = ["php83", "composer", "nodejs_20", "postgresql"]

[phases.install]
cmds = [
  "composer install --no-dev",
  "mkdir -p bootstrap/cache",
  "php artisan vendor:publish --provider=\"Spatie\\Permission\\PermissionServiceProvider\" --tag=config --force"
]

[phases.build]
cmds = [
  "npm ci",
  "npm run build"
]

[phases.migrate]
cmds = [
  "php artisan migrate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"